version: "3.9"
services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
      - redis
    command: ["python", "-m", "tgcrm.bot.main"]
  worker:
    build: .
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: ["celery", "-A", "tgcrm.tasks.celery_app.celery_app", "worker", "--loglevel=info"]
  beat:
    build: .
    env_file: .env
    depends_on:
      - worker
    command: ["celery", "-A", "tgcrm.tasks.celery_app.celery_app", "beat", "--loglevel=info"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
